// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetService_Project.Models;

public partial class TChatMessage
{
    public int FMessageId { get; set; }

    public int FSessionId { get; set; }

    public int FSenderId { get; set; }

    public string FSenderRole { get; set; }

    public string FMessageText { get; set; }

    public string FAttachmentUrl { get; set; }

    public string FMessageType { get; set; }

    public DateTime FSendTime { get; set; }

    public bool FIsRead { get; set; }

    public bool FIsDeleted { get; set; }

    public DateTime? FDeletedAt { get; set; }

    public virtual TChatSession FSession { get; set; }

}