// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetService_Project.Models;

public partial class TChatSession
{
    public int FSessionId { get; set; }

    public int FMemberId { get; set; }

    public int FEmployeeId { get; set; }

    public DateTime FStartTime { get; set; }

    public DateTime? FEndTime { get; set; }

    public string Status { get; set; }

    public DateTime? FLastMessageTime { get; set; }

    public virtual TEmployee FEmployee { get; set; }

    public virtual TMember FMember { get; set; }

    public virtual ICollection<TChatMessage> TChatMessages { get; set; } = new List<TChatMessage>();
}