// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetService_Project.Models;

public partial class TDistrict
{
    public int FId { get; set; }

    public string FDistrictName { get; set; }

    public bool FIsDelete { get; set; }

    public virtual ICollection<TEmployeeService> TEmployeeServices { get; set; } = new List<TEmployeeService>();
}