// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetService_Project.Models;

public partial class TEmployeePhoto
{
    public int FId { get; set; }

    public int FEmployeeId { get; set; }

    public string FImagepath { get; set; }

    public virtual TEmployee FEmployee { get; set; }
}