// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetService_Project.Models;

public partial class TEmployeeService
{
    public int FId { get; set; }

    public int FEmployeeId { get; set; }

    public int FDistrictId { get; set; }

    public string FDescriptionShort { get; set; }

    public string FDescription { get; set; }

    public int FAcceptPetType { get; set; }

    public int FPetSize { get; set; }

    public int? FDistance { get; set; }

    public decimal? FPrice { get; set; }

    public decimal? FLatitude { get; set; }

    public decimal? FLongitude { get; set; }

    public bool FIsDelete { get; set; }

    public virtual TDistrict FDistrict { get; set; }

    public virtual TEmployee FEmployee { get; set; }

    public virtual ICollection<TOrderWalkDetail> TOrderWalkDetails { get; set; } = new List<TOrderWalkDetail>();
}