// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetService_Project.Models;

public partial class TEmployee
{
    public int FId { get; set; }

    public string FName { get; set; }

    public string FPhone { get; set; }

    public string FEmail { get; set; }

    public string FGender { get; set; }

    public DateTime? FBirth { get; set; }

    public string FAddress { get; set; }

    public DateTime? FCreatedAt { get; set; }

    public int? FPosition { get; set; }

    public string FAccount { get; set; }

    public string FPassword { get; set; }

    public string FImage { get; set; }

    public virtual ICollection<TChatSession> TChatSessions { get; set; } = new List<TChatSession>();

    public virtual ICollection<TEmployeePhoto> TEmployeePhotos { get; set; } = new List<TEmployeePhoto>();

    public virtual ICollection<TEmployeeService> TEmployeeServices { get; set; } = new List<TEmployeeService>();
}