// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetService_Project.Models;

public partial class TFaq
{
    public int FId { get; set; }

    public string FQuestion { get; set; }

    public string FAnswer { get; set; }

    public string FCategory { get; set; }

    public int? FSortOrder { get; set; }

    public bool? FIsActive { get; set; }

    public DateTime? FCreateDate { get; set; }
}