// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetService_Project.Models;

public partial class THotelItem
{
    public int FId { get; set; }

    public int FHotelId { get; set; }

    public int FType { get; set; }

    public string FName { get; set; }

    public string FDescription { get; set; }

    public bool FIsDelete { get; set; }

    public virtual THotel FHotel { get; set; }
}