// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetService_Project.Models;

public partial class THotel
{
    public int FId { get; set; }

    public string FName { get; set; }

    public string FPhone { get; set; }

    public string FAddress { get; set; }

    public string FEmail { get; set; }

    public decimal? FLongitude { get; set; }

    public decimal? FLatitude { get; set; }

    public string FImage1 { get; set; }

    public string FImage2 { get; set; }

    public string FImage3 { get; set; }

    public bool FIsDelete { get; set; }
    public byte? FRating { get; set; }
    public virtual ICollection<THotelItem> TTotalItems { get; set; } = new List<THotelItem>();

    public virtual ICollection<THotelItem> THotelItems { get; set; } = new List<THotelItem>();

    public virtual ICollection<THotelReview> THotelReviews { get; set; } = new List<THotelReview>();

    public virtual ICollection<TOrderHotelDetail> TOrderHotelDetails { get; set; } = new List<TOrderHotelDetail>();

    public virtual ICollection<TQtyStatus> TQtyStatuses { get; set; } = new List<TQtyStatus>();

    public virtual ICollection<TRoomsDetail> TRoomsDetails { get; set; } = new List<TRoomsDetail>();
}