// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetService_Project.Models;

public partial class TMemberSource
{
    public int FMemberId { get; set; }

    public int FSourceId { get; set; }

    public virtual TMember FMember { get; set; }

    public virtual TSourceList FSource { get; set; }
}