// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetService_Project.Models;

public partial class TMember
{
    
    public int FId { get; set; }

    public string FName { get; set; }

    public string FEmail { get; set; }

    public bool? FEmailVerfifcation { get; set; }

    public string FPassword { get; set; }

    public string FPhone { get; set; }

    public string FAddress { get; set; }

    public DateTime? FCreatedDate { get; set; }

    public string FInfo { get; set; }

    public string FImage { get; set; }

    public bool? FBlackList { get; set; }

    public bool FIsDeleted { get; set; }

    public string FAspNetUserId { get; set; }

    public string FGoogleAvatarUrl { get; set; }

    public string FProviderKey { get; set; }

    public DateTime? FLastLoginDate { get; set; }

    public string FLoginProvider { get; set; }

    public virtual ICollection<TChatSession> TChatSessions { get; set; } = new List<TChatSession>();

    public virtual ICollection<THotelReview> THotelReviews { get; set; } = new List<THotelReview>();

    public virtual ICollection<TPetList> TPetLists { get; set; } = new List<TPetList>();

    public virtual ICollection<TWalkReview> TWalkReviews { get; set; } = new List<TWalkReview>();
    public virtual ICollection<TMemberSource> TMemberSources { get; set; } = new List<TMemberSource>();
}