// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetService_Project.Models;

public partial class TNews
{
    public int FId { get; set; }

    public string FTitle { get; set; }

    public string FContent { get; set; }

    public string FCategory { get; set; }

    public DateTime? FStartDate { get; set; }

    public DateTime? FEndDate { get; set; }

    public bool? FIsPinned { get; set; }

    public bool? FIsActive { get; set; }

    public string FImagePath { get; set; }

    public DateTime? FCreateDate { get; set; }

    public virtual ICollection<TNewsFile> TNewsFiles { get; set; } = new List<TNewsFile>();
}