// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetService_Project.Models;

public partial class TOrderWalkDetail
{
    public int FId { get; set; }

    public int? FOrderId { get; set; }

    public int? FEmployeeServiceId { get; set; }

    public DateTime? FWalkStart { get; set; }

    public DateTime? FWalkEnd { get; set; }

    public decimal? FServicePrice { get; set; }

    public decimal? FTotalPrice { get; set; }

    public int? FAmount { get; set; }

    public string FAdditionlＭessage { get; set; }

    public virtual TEmployeeService FEmployeeService { get; set; }

    public virtual TOrder FOrder { get; set; }
}