// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetService_Project.Models;

public partial class TOrderHotelDetail
{
    public int FId { get; set; }

    public int? FOrderId { get; set; }

    public int? FHotelId { get; set; }

    public int? FRoomDetailId { get; set; }

    public DateTime? FCheckIn { get; set; }

    public DateTime? FCheckOut { get; set; }

    public int? FRoomQty { get; set; }

    public decimal? FPricePerRoom { get; set; }

    public decimal? FTotalPrice { get; set; }

    public string FAdditionlMessage { get; set; }

    public virtual THotel FHotel { get; set; }

    public virtual TOrder FOrder { get; set; }

    public virtual TRoomsDetail FRoomDetail { get; set; }
}