// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetService_Project.Models;

public partial class TOrder
{
    public int FId { get; set; }

    public int? FMemberId { get; set; }

    public string FOrderType { get; set; }

    public string FOrderStatus { get; set; }

    public decimal? FTotalAmount { get; set; }

    public DateTime? FCreatedAt { get; set; }

    public DateTime? FUpdatedAt { get; set; }

    public bool FIsDelete { get; set; }

    public virtual ICollection<THotelReview> THotelReviews { get; set; } = new List<THotelReview>();

    public virtual ICollection<TOrderHotelDetail> TOrderHotelDetails { get; set; } = new List<TOrderHotelDetail>();

    public virtual ICollection<TOrderWalkDetail> TOrderWalkDetails { get; set; } = new List<TOrderWalkDetail>();

    public virtual ICollection<TWalkReview> TWalkReviews { get; set; } = new List<TWalkReview>();
}