// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetService_Project.Models;

public partial class TPetList
{
    public int FId { get; set; }

    public int FMemberId { get; set; }

    public string FPetName { get; set; }

    public int? FPetWeight { get; set; }

    public int? FPetAge { get; set; }

    public int? FPetDe { get; set; }

    public int? FPetTrained { get; set; }

    public int? FPetChildFriendly { get; set; }

    public int? FPetPetFriendly { get; set; }

    public string FPetMemo { get; set; }

    public int? FPetBlackList { get; set; }

    public DateTime? FPetBirthday { get; set; }

    public string FPetImagePath { get; set; }

    public virtual TMember FMember { get; set; }
}