// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetService_Project.Models;

public partial class TPriceFluctuation
{
    public int FId { get; set; }

    public int? FMonth { get; set; }

    public decimal? FMultiplier { get; set; }
}