// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetService_Project.Models;

public partial class TRoomType
{
    public int FId { get; set; }

    public string FName { get; set; }

    public virtual ICollection<THotelReview> THotelReviews { get; set; } = new List<THotelReview>();

    public virtual ICollection<TRoomsDetail> TRoomsDetails { get; set; } = new List<TRoomsDetail>();
}