// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetService_Project.Models;

public partial class TRoomsDetail
{
    public int FId { get; set; }

    public int? FHotelId { get; set; }

    public int? FRoomtypeId { get; set; }

    public decimal? FPrice { get; set; }

    public int? FQty { get; set; }

    public string FImage { get; set; }

    public bool FIsDelete { get; set; }

    public string FRoom_size { get; set; }

    public virtual THotel FHotel { get; set; }

    public virtual TRoomType FRoomtype { get; set; }

    public virtual ICollection<TOrderHotelDetail> TOrderHotelDetails { get; set; } = new List<TOrderHotelDetail>();
}