// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetService_Project.Models;

public partial class TSourceList
{
    public int FSourceId { get; set; }

    public string FSourceName { get; set; }
    public virtual ICollection<TMemberSource> TMemberSources { get; set; } = new List<TMemberSource>();
}