// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PetService_Project.Models;

public partial class TWalkReview
{
    public int FId { get; set; }

    public int FMemberId { get; set; }

    public int FEmployeeId { get; set; }

    public int FOrderId { get; set; }

    public DateTime? FCreatedAt { get; set; }

    public byte? FRating { get; set; }

    public string FContent { get; set; }

    public bool FIsDelete { get; set; }

    public DateTime? FUpdatedAt { get; set; }

    public virtual TMember FMember { get; set; }

    public virtual TOrder FOrder { get; set; }
}